"""
Numba parallel JIT crash reproducer — for Numba issue tracker.

Environment:
  - Python 3.11, Numba 0.60.0, numpy 2.0.2, Linux x86_64

How to reproduce:
    $ python segfault_mwe.py

Expected result:
    Call 1...
    Segmentation fault (SIGSEGV, exit 139)

Root cause:
  The crash is NOT a Numba bug — it is an out-of-bounds array access in
  the generated coupling function.  The inner loop iterates over
  n_tgt_nodes = 68, but the inter-projection target (thalamus) only has
  8 nodes.  The `c_b` coupling scratch array has shape (1, 8, 1); when
  j >= 8, `tgt[target_cvar[ic], j, 0]` writes past the end of the
  array, corrupting the heap and causing a segfault.

  boundscheck=True "fixes" the crash only because Numba silently
  ignores the flag when parallel=True; the altered compilation path
  happens to avoid the corruption.

Fix:
  The real fix is in tvb_library/tvb/simulator/backend/nb_hybrid.py:
  ProjectionInfo.n_tgt_nodes must return the ACTUAL target node count
  (p.target.nnodes for inter-projections), not the CSR row count
  (weights_indptr.shape[0] - 1).

Context:
  This module is auto-generated by TVB's nb-hybrid backend for a
  multi-subnet Jansen-Rit model.  The crash reproduces with real
  connectivity data and the exact code paths TVB generates.
"""

import numpy as np
import numba as nb


# ---- Auto-generated coupling functions (from TVB backend) ----

@nb.njit(inline="always", cache=True)
def compute_coupling_cortex_to_thalamus(
    srcbuf,
    w_data, w_indices, w_indptr,
    idelays,
    mode_map,
    source_cvar,
    target_cvar,
    scale,
    target_scales,
    cfun_params,
    t,
    tgt,
):
    """BUG: loops range(68) but tgt only has 8 elements."""
    n_src_cvar = source_cvar.shape[0]
    has_ts = target_scales.shape[0] > 0

    for j in range(68):      # <<< BUG: should be range(8)
        row_start = w_indptr[j]
        row_end = w_indptr[j + 1]

        for ic in range(n_src_cvar):
            cv = source_cvar[ic]
            wsum = nb.float32(0.0)
            for ptr in range(row_start, row_end):
                w = w_data[ptr]
                src_node = w_indices[ptr]
                buf_idx = (t - 1 - idelays[ptr] + 1) % 1
                wsum += w * srcbuf[cv, src_node, 0, buf_idx]
            wsum *= scale
            wsum = cfun_params[0] * wsum + cfun_params[1]

            contrib = wsum * mode_map[0, 0]
            ts = target_scales[ic] if has_ts else nb.float32(1.0)
            tgt[target_cvar[ic], j, 0] += ts * contrib


@nb.njit(inline="always", cache=True)
def compute_coupling_intra(
    srcbuf,
    w_data, w_indices, w_indptr,
    idelays,
    source_cvar,
    target_cvar,
    scale,
    target_scales,
    cfun_params,
    t,
    tgt,
):
    """Intra-projection: loops range(68), tgt has 68 elements — correct."""
    n_src_cvar = source_cvar.shape[0]
    has_ts = target_scales.shape[0] > 0

    for j in range(68):
        row_start = w_indptr[j]
        row_end = w_indptr[j + 1]

        for ic in range(n_src_cvar):
            cv = source_cvar[ic]
            wsum = nb.float32(0.0)
            for ptr in range(row_start, row_end):
                w = w_data[ptr]
                src_node = w_indices[ptr]
                buf_idx = (t - 1 - idelays[ptr] + 1) % 1
                wsum += w * srcbuf[cv, src_node, 0, buf_idx]
            wsum *= scale
            wsum = cfun_params[0] * wsum + cfun_params[1]
            ts = target_scales[ic] if has_ts else nb.float32(1.0)
            tgt[target_cvar[ic], j, 0] += ts * wsum


# The rest of network_chunk and sweep_kernel are omitted for brevity.
# The full 776-line module that triggers the crash is available in the
# TVB repository (generated at runtime from Mako templates).


if __name__ == "__main__":
    N_C = 68
    N_T = 8

    # Build args that trigger the OOB
    inter_w_indptr = np.arange(N_T + 1, dtype=np.int32)   # 9 entries
    intra_w_indptr = np.arange(N_C + 1, dtype=np.int32)   # 69 entries

    # coupling scratch for thalamus — only 8 target nodes
    c_b = np.zeros((1, N_T, 1), dtype=np.float32)

    # call with j=68 but c_b only has shape (1, 8, 1)
    print("Calling compute_coupling_cortex_to_thalamus with j=68 & tgt.shape=(1,8,1)...")
    compute_coupling_cortex_to_thalamus(
        np.zeros((1, N_C, 1, 1), dtype=np.float32),   # srcbuf
        np.ones(20, dtype=np.float32),                  # w_data
        np.zeros(20, dtype=np.int32),                   # w_indices
        inter_w_indptr,                                  # w_indptr (9 entries)
        np.zeros(20, dtype=np.int32),                   # idelays
        np.ones((1, 1), dtype=np.float32),             # mode_map
        np.array([1], dtype=np.int32),                  # source_cvar
        np.array([0], dtype=np.int32),                  # target_cvar
        np.float32(1.0),                               # scale
        np.zeros(0, dtype=np.float32),                  # target_scales
        np.ones(8, dtype=np.float32) * 0.01,           # cfun_params
        np.int32(1),                                    # t
        c_b,                                            # tgt (shape 1,8,1)
    )
    print("If you see this, the crash was avoided (likely by Numba's codegen path).")
    print("Run with boundscheck=True on the decorator to see IndexError.")
