[parameters]
# all these shall become numpy arrays when loaded
C_m = 150.0
E_L_e = -65.0
E_L_i = -65.0
E_e = 0.0
E_i = -80.0
K_ext_e = 400
K_ext_i = 100 # this is weirdly set to 0 by default as the external drive is excitatory
N_tot = 10000
P_e = [ -49.8e-3, 5.06e-3,  -23.4e-3,  2.3e-3, -0.41e-3, 10.5e-3, -36.6e-3, 7.4e-3, 1.2e-3, -40.7e-3 ]
P_i = [ -51.5e-3,  4.0e-3,  -8.35e-3, 0.24e-3, -0.50e-3, 1.43e-3, -14.7e-3, 4.5e-3, 2.8e-3, -15.3e-3 ]
Q_e = 1.5
Q_i = 5.0
T = 5.0
a_e = 4.0
a_i = 0.0
b_e = 60.0
b_i = 0.0
external_input_ex_ex = 4e-3#0.315e-3
external_input_ex_in = 0.000
external_input_in_ex = 4e-3#0.315e-3
external_input_in_in = 0.000
g = 0.2
g_L = 10.0
p_connect_e = 0.05
p_connect_i = 0.05
tau_OU = 5.0
tau_e = 5.0
tau_i = 5.0
tau_w_e = 500.0
tau_w_i = 1.0
weight_noise = 1e-4

[attributes]
# these are approached on a case-by-case basis
stvar = [7] 
variables_of_interest=['E', 'I', 'C_ee', 'C_ei', 'C_ii', 'W_e', 'W_i', 'ou_drift']
state_variable_range.E = [0.0022, 0.0022] 
state_variable_range.I = [0.01448, 0.01448]
state_variable_range.C_ee = [0.0, 0.0]
state_variable_range.C_ei = [0.0, 0.0]
state_variable_range.C_ii = [0.0, 0.0]
state_variable_range.W_e = [103.0, 103.0] 
state_variable_range.W_i = [0.0, 0.0]
state_variable_range.ou_drift = [0.0, 0.0]

