#!/bin/bash
# make sure system knows where TVB libraries are located:

# This should always be places at /home/tvbadmin/clusterLauncher since that is the command we use in cluster settings
export TVB_ROOT=/home/tvbadmin/TVB_Distribution
export PATH=$TVB_ROOT/tvb_data/bin:$PATH

if [ ! ${TVB_ROOT+1} ]; then
        echo "ERROR:    TVB_ROOT environment variable is required!!!"
        exit 1
fi

export PYTHONPATH=$TVB_ROOT/tvb_data/lib/python3.7:$TVB_ROOT/tvb_data/lib/python3.7/site-packages
unset PYTHONHOME

if [ ${LD_LIBRARY_PATH+1} ]; then
   export LD_LIBRARY_PATH=$TVB_ROOT/tvb_data/lib:$TVB_ROOT/tvb_data/bin:$LD_LIBRARY_PATH
else
   export LD_LIBRARY_PATH=$TVB_ROOT/tvb_data/lib:$TVB_ROOT/tvb_data/bin
fi

if [ ${LD_RUN_PATH+1} ]; then
   export LD_RUN_PATH=$TVB_ROOT/tvb_data/lib:$TVB_ROOT/tvb_data/bin:$LD_RUN_PATH
else
   export LD_RUN_PATH=$TVB_ROOT/tvb_data/lib:$TVB_ROOT/tvb_data/bin
fi

echo "Starting TVB with python from TVB-Distribution"
echo $TVB_ROOT, $1

$TVB_ROOT/tvb_data/bin/python -m tvb.core.operation_async_launcher $1 WEB_PROFILE