#!/bin/bash
# make sure system knows where TVB libraries are located:

# This should always be places at /home/tvbadmin/clusterLauncher since that is the command we use in cluster settings
export TVB_ROOT=/home/tvbadmin/TVB_Distribution
export PATH=$TVB_ROOT:$PATH

if [ ! ${TVB_ROOT+1} ]; then
        echo "ERROR:    TVB_ROOT environment variable is required!!!"
        exit 1
fi

export PYTHONPATH=$TVB_ROOT/tvb_data
export PYTHONHOME=$TVB_ROOT/tvb_data

if [ ${LD_LIBRARY_PATH+1} ]; then
   export LD_LIBRARY_PATH=$TVB_ROOT/tvb_data:$LD_LIBRARY_PATH
else
   export LD_LIBRARY_PATH=$TVB_ROOT/tvb_data
fi
 
if [ ${LD_RUN_PATH+1} ]; then
   export LD_RUN_PATH=$TVB_ROOT/tvb_data:$LD_RUN_PATH
else
   export LD_RUN_PATH=$TVB_ROOT/tvb_data
fi

$TVB_ROOT/tvb_data/exe/python -m tvb.core.operation_async_launcher $1