#!/bin/sh

#echo "Pulling tvb-run docker image"
#/apps/daint/system/opt/sarus/1.0.1/bin/sarus pull thevirtualbrain/tvb-run:tvb-rest

start=$SECONDS

echo "Start docker container"
#srun -C mc /apps/daint/system/opt/sarus/1.0.1/bin/sarus --debug run --mpi --mount=type=bind,source=$PWD,destination=$PWD thevirtualbrain/tvb-run:tvb-hpc /bin/bash -c "cd $PWD && /home/docker/env/neurosci/bin/python -m tvb.core.operation_hpc_launcher $1 $2 $3"
docker run -v $INPUT_HPC_FOLDER:/root/input_hpc -v $TVB_ROOT_FOLDER:/root/tvb-root tvb-run-hpc /bin/bash -c "source activate tvb-run && python -m tvb.core.operation_hpc_launcher $1 $2 $3"

duration=$(( SECONDS - start ))

echo "TVB operation run completed in $duration seconds"
