#!/bin/sh

#echo "Pulling tvb-run docker image"
/apps/daint/system/opt/sarus/1.1.0/bin/sarus pull thevirtualbrain/tvb-run:tvb-hpc

start=$SECONDS

echo "Start docker container"
srun -C mc /apps/daint/system/opt/sarus/1.1.0/bin/sarus --debug run --mount=type=bind,source=$PWD,destination=$PWD thevirtualbrain/tvb-run:tvb-hpc /bin/bash -c "cd $PWD && /opt/conda/envs/tvb-run/bin/python -m tvb.core.operation_hpc_launcher $1 $2 $3"

duration=$(( SECONDS - start ))

echo "TVB operation run completed in $duration seconds"
