#!/bin/sh

#echo "Pulling tvb-run docker image"
/apps/daint/system/opt/sarus/1.1.0/bin/sarus pull thevirtualbrain/tvb-run:tvb-hpc

start=$SECONDS

echo "Start docker container"
mkdir TVB_STORAGE
srun -C mc /apps/daint/system/opt/sarus/1.1.0/bin/sarus --debug run --mount=type=bind,source=$PWD/data,destination=$5 --mount=type=bind,source=$PWD/TVB_STORAGE,destination=/root/TVB_STORAGE --mount=type=bind,source=$HOME,destination=$6 thevirtualbrain/tvb-run:tvb-hpc /bin/bash -c "/opt/conda/envs/tvb-run/bin/python -m tvb.core.operation_hpc_launcher $1 $2 $3 $4 $7"

duration=$(( SECONDS - start ))

echo "TVB operation run completed in $duration seconds"
