# -*- coding: utf-8 -*-
"""Expression-driven C++ dfun generator for the CppHybrid backend.

TVB models declare their derivatives as Python expression strings
(``state_variable_dfuns``) plus optional ``dfun_intermediates``,
``dfun_helpers`` and ``dfun_constants``.  This module translates those
expressions into small per-model C++ dfun functions (one function per model,
SIMD-lane layout identical to the hand-written kernels).  Code *emission*
(``emit_sources``) is deliberately separate from *compilation*: the package
build can emit the source once and compile it into the nanobind extension,
while ``generate_lib`` keeps the runtime g++/ctypes fallback for user-defined
models.  ``python -m tvb.simulator.backend.cpp_hybrid.dfungen --emit PATH`` is
the CLI entry point the build invokes.

This is NOT monolithic kernel generation: only per-model derivative
functions are emitted; all control flow (integration, coupling, monitors,
sweeps) stays in the prebuilt C++ core.
"""

import ast
import importlib
import inspect
import json
import os
import subprocess
import sys
import textwrap
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# expression translation
# ---------------------------------------------------------------------------

_FN_MAP = {
    "sin": "sin", "cos": "cos", "tan": "tan", "exp": "exp", "log": "log",
    "log10": "log10", "sqrt": "sqrt", "tanh": "tanh", "sinh": "sinh",
    "cosh": "cosh", "atan": "atan", "asin": "asin", "acos": "acos",
    "abs": "fabs", "fabs": "fabs", "floor": "floor", "ceil": "ceil",
    "sign": "cph_sign", "minimum": "fmin", "maximum": "fmax",
    "pow": "pow", "arctan": "atan", "arcsin": "asin", "arccos": "acos",
    "log1p": "log1p", "expm1": "expm1", "hypot": "hypot", "cbrt": "cbrt",
}

_PRELUDE = r"""
#include <cmath>
#include <cstdint>
#include <complex>
#include <algorithm>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

static inline double cph_sign(double v) { return v > 0 ? 1.0 : (v < 0 ? -1.0 : 0.0); }
static inline double cph_pow(double b, double e) {
  // python ** semantics; complex when the base would be negative
  if (b >= 0.0 || std::floor(e) == e) return std::pow(b, e);
  return std::pow(std::complex<double>(b, 0.0), e).real();
}
static inline std::complex<double> cph_pow(std::complex<double> b, double e) {
  return std::pow(b, e);
}
static inline std::complex<double> cplx(double v) { return {v, 0.0}; }
static inline std::complex<double> cplx(const std::complex<double> &v) { return v; }

/* The prebuilt extension is compiled with -fvisibility=hidden, which would
 * keep the entry points below out of the module's dynamic symbol table.
 * Default visibility keeps them inspectable (nm -D) and callable from the
 * core TU.  MSVC has no visibility attributes; there the symbols only need to
 * be reachable inside the module, so the macro expands to nothing. */
#if defined(_MSC_VER) || defined(__CYGWIN__)
#define CPH_GEN_EXPORT
#else
#define CPH_GEN_EXPORT __attribute__((visibility("default")))
#endif
"""

_GENERATED_BANNER = ("// Generated by tvb.simulator.backend.cpp_hybrid.dfungen "
                     "-- do not edit.")


class Expr2Cpp(ast.NodeVisitor):
    def __init__(self, names, ctx, helpers=(), allow_mode=False):
        self.names = names          # known identifiers
        self.ctx = ctx              # 'complex' if complex ops used
        self.helpers = set(helpers)
        self.allow_mode = allow_mode
        self.out = []

    def __call__(self, node):
        self.out.append(self.visit(node))
        return self.out[-1]

    def visit_Name(self, node):
        n = node.id
        if n in self.names:
            return n
        if self.allow_mode and n.endswith("_m"):
            base = n[:-2]
            if base in self.names:
                return base
        raise ValueError(f"unknown identifier {n!r}")

    def visit_Constant(self, node):
        v = node.value
        if isinstance(v, complex):
            self.ctx["complex"] = True
            return f"std::complex<double>({v.real!r}, {v.imag!r})"
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, (int, float)):
            return repr(float(v))
        raise ValueError(f"unsupported constant {v!r}")

    def visit_BinOp(self, node):
        l, r = self.visit(node.left), self.visit(node.right)
        op = type(node.op)
        if op is ast.Pow:
            # complex-safe power
            self.ctx["complex_maybe"] = True
            return f"cph_pow({l}, {r})"
        sym = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Div: "/",
               ast.Mod: "fmod", ast.LShift: "<<", ast.RShift: ">>",
               ast.BitAnd: "&", ast.BitOr: "|", ast.BitXor: "^"}.get(op)
        if sym is None:
            raise ValueError(f"unsupported binop {op}")
        return f"({l} {sym} {r})"

    def visit_UnaryOp(self, node):
        v = self.visit(node.operand)
        if isinstance(node.op, ast.USub):
            return f"(-{v})"
        if isinstance(node.op, ast.UAdd):
            return f"(+{v})"
        if isinstance(node.op, ast.Not):
            return f"(!(bool)({v}))"
        raise ValueError("unsupported unaryop")

    def visit_Compare(self, node):
        l = self.visit(node.left)
        out = None
        for op, comp in zip(node.ops, node.comparators):
            r = self.visit(comp)
            sym = {ast.Lt: "<", ast.Gt: ">", ast.LtE: "<=", ast.GtE: ">=",
                   ast.Eq: "==", ast.NotEq: "!=", ast.In: "==",
                   ast.NotIn: "!="}.get(type(op))
            if sym is None:
                raise ValueError(f"unsupported cmp {op}")
            expr = f"({l} {sym} {r})"
            out = expr if out is None else f"(({out}) && ({expr}))"
            l = r
        return out

    def visit_BoolOp(self, node):
        sym = "&&" if isinstance(node.op, ast.And) else "||"
        parts = [f"(bool)({self.visit(v)})" for v in node.values]
        return "(" + f" {sym} ".join(parts) + ")"

    def visit_Call(self, node):
        fname = None
        if isinstance(node.func, ast.Name):
            fname = node.func.id
        elif isinstance(node.func, ast.Attribute):
            fname = node.func.attr
        if fname == "float32":  # nb.float32 / np.float32 casts
            return f"(double)({self.visit(node.args[0])})"
        if fname in self.helpers:
            args = ", ".join(self.visit(a) for a in node.args)
            return f"{fname}({args})"
        if fname in _FN_MAP:
            args = ", ".join(self.visit(a) for a in node.args)
            return f"{_FN_MAP[fname]}({args})"
        if fname == "where":
            c, a, b = (self.visit(x) for x in node.args)
            return f"(({c}) ? ({a}) : ({b}))"
        raise ValueError(f"unsupported function {fname!r}")

    def visit_Attribute(self, node):
        # math.pi / np.pi etc.
        base = node.value
        if isinstance(base, ast.Name) and base.id in ("math", "np", "numpy"):
            if node.attr == "pi":
                return "M_PI"
            if node.attr in _FN_MAP:
                return _FN_MAP[node.attr]
            raise ValueError(f"unsupported {base.id}.{node.attr}")
        v = self.visit(node.value)
        if node.attr == "real":
            self.ctx["complex"] = True
            return f"({v}).real()"
        if node.attr == "imag":
            self.ctx["complex"] = True
            return f"({v}).imag()"
        raise ValueError(f"unsupported attribute {node.attr!r}")

    def visit_IfExp(self, node):
        return (f"(({self.visit(node.test)}) ? ({self.visit(node.body)})"
                f" : ({self.visit(node.orelse)}))")

    def visit_Subscript(self, node):
        # e.g. theta[sliceT] — treat scalars as-is
        return self.visit(node.value)

    def visit_List(self, node):
        raise ValueError("lists unsupported in dfun expressions")


def cph_pow(l, r):
    return f"cph_pow({l}, {r})"


def translate(expr, names, ctx, helpers=(), allow_mode=False):
    expr = expr.replace("_{m}", "_m")  # reduced-set subscripts
    tree = ast.parse(expr.strip(), mode="eval")
    return Expr2Cpp(names, ctx, helpers, allow_mode=allow_mode)(tree.body)


# ---------------------------------------------------------------------------
# model collection
# ---------------------------------------------------------------------------

#: first id of the generated (expression-driven) dispatch range; the emitted
#: dispatcher maps model_id -> table index as (model_id - _FIRST_MODEL_ID), so
#: ids and the table must stay in lockstep
_FIRST_MODEL_ID = 100


class DfunGenerationError(RuntimeError):
    """Strict-mode failure: a model that should have produced a generated dfun
    did not.  Raised only when ``strict=True`` (the build-time path), where
    silently skipping a model would shrink model coverage unnoticed."""


def _exc_text(exc: BaseException) -> str:
    return f"{type(exc).__name__}: {exc}"


def _declares_dfuns(cls) -> bool:
    """Whether a Model subclass declares ``state_variable_dfuns`` in a class
    body (as a neotraits ``Final`` trait or as a plain dict), i.e. it is meant
    to be expression-driven.  Models that do not (the numba-only Zerlaut and
    CerebellarMF kernels) are not generic-dfun candidates and must not be
    reported as strict-mode failures."""
    return any("state_variable_dfuns" in vars(c) for c in cls.__mro__)


def _failure_report(failures) -> str:
    """Aggregate strict-mode failures into one message; each offender is one
    ``module.Class: <stage> <exception text>`` line."""
    counts = {}
    for _, stage, _ in failures:
        counts[stage] = counts.get(stage, 0) + 1
    summary = ", ".join(f"{n} {stage} failure(s)"
                        for stage, n in sorted(counts.items()))
    detail = "\n".join(f"  {name}: {stage} {text}"
                       for name, stage, text in failures)
    return (f"strict dfun generation failed ({summary}); every offender is "
            f"listed below:\n{detail}")


def _collect_models():
    """Discover expression-driven models.

    Returns ``(models, failures)``: ``models`` maps model class name to a
    configured instance, ``failures`` lists ``(qualified_name, stage,
    exception_text)`` for model modules that could not be imported and concrete
    ``state_variable_dfuns`` classes that could not be instantiated/configured.
    Abstract scaffolding (``ModelNumbaDfun``, ``ReducedSetBase``) is skipped: it
    is not a model, so its absence is not a coverage loss.  Failures are always
    collected and never raised here; callers decide whether to report them
    (``collect_models``/``emit_sources`` with ``strict=True``) or ignore them.
    """
    import pkgutil
    from tvb.simulator.models.base import Model
    import tvb.simulator.models as pkg

    models = {}
    failures = []
    mods = []
    if hasattr(pkg, '__path__'):
        for mi in pkgutil.iter_modules(pkg.__path__):
            mod_name = f"tvb.simulator.models.{mi.name}"
            try:
                mods.append(importlib.import_module(mod_name))
            except Exception as exc:
                failures.append((mod_name, "import", _exc_text(exc)))
    else:
        mods = [getattr(pkg, m) for m in dir(pkg)
                if inspect.ismodule(getattr(pkg, m))]

    seen = set()
    for mod in mods:
        for cn in dir(mod):
            cls = getattr(mod, cn)
            if not (isinstance(cls, type) and issubclass(cls, Model)
                    and cls is not Model):
                continue
            if cls in seen or cn in models:
                continue
            seen.add(cls)
            if inspect.isabstract(cls):
                continue
            generic_candidate = _declares_dfuns(cls)
            try:
                o = cls()
                o.configure()
            except Exception as exc:
                if generic_candidate:
                    failures.append((f"{cls.__module__}.{cls.__name__}",
                                     "configure", _exc_text(exc)))
                continue
            svd = getattr(o, "state_variable_dfuns", None)
            if isinstance(svd, dict) and svd:
                models[cn] = o
    return models, failures


def collect_models(strict: bool = False):
    """Map model class name -> configured instance for all expression-driven
    models (those declaring state_variable_dfuns).

    ``strict=False`` (the runtime default) keeps today's lenient behaviour and
    silently skips what cannot be built; ``strict=True`` raises
    ``DfunGenerationError`` listing every failure instead.
    """
    models, failures = _collect_models()
    if strict and failures:
        raise DfunGenerationError(_failure_report(failures))
    return models


# ---------------------------------------------------------------------------
# C++ emission
# ---------------------------------------------------------------------------

def _emit_model(mid, model, fns):
    """Emit one per-model dfun kernel, named ``dfun_gen_<mid>``, for ``model``.

    Returns ``(code, n_parm, n_cvar, n_svar, parm_names)``; ``parm_names`` is
    the ordered global+spatial parameter list the kernel indexes ``parr`` with
    (the single source of truth for parameter packing), and ``n_cvar`` is the
    raw coupling-term count — callers clamp it to >= 1 to match the emitted
    ``n_cvar`` local.  ``fns`` is unused (kept for call-site compatibility).
    """
    svars = list(model.state_variables)
    cvars = list(model.coupling_terms) if getattr(model, "coupling_terms", None) else []
    globals_ = list(model.global_parameter_names)
    spatial = list(model.spatial_parameter_names)
    params = globals_ + spatial
    constants = getattr(model, "dfun_constants", None) or {}
    helpers = getattr(model, "dfun_helpers", None) or []
    inter = getattr(model, "dfun_intermediates", None) or []

    is_combined = getattr(model, "dfun_mode", None) == "combined"
    dm_names = (list(getattr(model, "derived_matrix_names", [])) if is_combined
                else [])
    dm_ops = (list(getattr(model, "derived_matrix_ops", [])) if is_combined
              else [])
    op_names = [op[0] for op in dm_ops]
    dm_data = {}
    if is_combined:
        for dn in dm_names:
            arr = getattr(model, dn, None)
            if arr is not None:
                dm_data[dn] = np.asarray(arr, dtype=np.float32).ravel()

    ctx = {}
    helper_names = {h[0] for h in helpers}
    helpers = list(helpers)
    known = (set(params) | set(constants) | set(svars) | set(cvars)
             | {"pi"} | helper_names | set(dm_names) | set(op_names))
    translated_inter = []
    for iname, iexpr in inter:
        translated_inter.append((iname, translate(iexpr, known, ctx, helper_names,
                                                  allow_mode=is_combined)))
        known.add(iname)
    translated_dx = []
    for sv in svars:
        translated_dx.append(
            (sv, translate(model.state_variable_dfuns[sv], known, ctx, helper_names,
                           allow_mode=is_combined)))
    use_complex = bool(ctx.get("complex"))
    T = "std::complex<double>" if use_complex else "double"
    wrap = (lambda e: f"cplx({e})") if use_complex else (lambda e: f"({e})")

    lines = []
    fn_name = f"dfun_gen_{mid}"
    for hname, hargs, hexpr in helpers:
        arg_names = [a.strip() for a in hargs.split(",")]
        body = translate(hexpr, set(arg_names) | set(constants), ctx, helper_names,
                         allow_mode=is_combined)
        decls = "".join(
            f"  const double {cname} = {float(cval)!r};\n"
            for cname, cval in constants.items())
        lines.append(
            f"static inline double {hname}({', '.join(f'double {a}' for a in arg_names)}) {{\n"
            f"{decls}"
            f"  return {body};\n}}")

    lines.append(
        f"static void {fn_name}(float *__restrict dxarr, "
        f"const float *__restrict xarr, "
        f"int node, int mode, int n_node, int n_modes, "
        f"const float *__restrict carr, "
        f"const float *__restrict parr, int n_parm, int Wn) {{")
    lines.append(f"  const int n_svar = {len(svars)}, n_cvar = {max(len(cvars), 1)};")
    lines.append("  (void)n_svar; (void)n_cvar; (void)n_parm;")
    if not cvars:
        lines.append("  (void)carr;")
    lines.append("  const size_t sw = (size_t)n_modes * (size_t)Wn;")
    lines.append("  const size_t nb = ((size_t)node * (size_t)n_modes + (size_t)mode) * (size_t)Wn;")
    if is_combined:
        for dn in dm_names:
            d = dm_data.get(dn)
            if d is not None:
                lines.append(
                    f"  const double {dn}_lit[{d.size}] = "
                    f"{{ {', '.join(repr(float(x)) for x in d)} }};")
    lines.append("  const float *pk = parr + (size_t)node * n_parm * Wn;")
    lines.append("  (void)pk;")
    lines.append("  for (int i = 0; i < Wn; i++) {")
    lines.append("    const double pi = M_PI; (void)pi;")
    for k, name in enumerate(params):
        if use_complex:
            lines.append(f"    const std::complex<double> {name} = cplx((double)parr[{k} * Wn + i]);")
        else:
            lines.append(f"    const double {name} = (double)parr[{k} * Wn + i];")
    for cname, cval in constants.items():
        lines.append(f"    const double {cname} = {float(cval)!r};")
    for si, sv in enumerate(svars):
        lines.append(
            f"    const {T} {sv} = {wrap(f'xarr[(size_t){si} * (size_t)n_node * sw + nb + i]')};")
    if is_combined:
        # mode-indexed derived vector constants
        for dn in dm_names:
            d = dm_data.get(dn)
            if d is not None and d.size > 1:
                # Aik/Bik/Cik are matrices (only used in ops); the per-mode
                # scalars sit at index == n_modes
                lines.append(
                    f"    const double {dn} = {dn}_lit[((size_t)mode)];")
        # coupling summed over source modes (combined-mode convention)
        for ci, cv in enumerate(cvars):
            lines.append(f"    double {cv} = 0.0;")
            lines.append(
                f"    for (int jj = 0; jj < n_modes; jj++) "
                f"{cv} += carr[((size_t){ci} * (size_t)n_node * sw + nb"
                f" - ((size_t)mode)*Wn + (size_t)jj * Wn + i)];")
        # derived op intermediates: sum over source modes using matrix[mk][mode]
        for op_name, op_mat, op_svar in dm_ops:
            lines.append(f"    double {op_name} = 0.0;")
            lines.append(
                f"    for (int jj = 0; jj < n_modes; jj++) "
                f"{op_name} += {op_mat}_lit[(size_t)jj * (size_t)n_modes + (size_t)mode] * "
                f"xarr[((size_t){svars.index(op_svar)} * (size_t)n_node * sw + nb"
                f" - ((size_t)mode) * Wn + (size_t)jj * Wn + i)];")
    else:
        for ci, cv in enumerate(cvars):
            lines.append(
                f"    const {T} {cv} = {wrap(f'carr[(size_t){ci} * (size_t)n_node * sw + nb + i]')};")
    for iname, code in translated_inter:
        lines.append(f"    const {T} {iname} = {wrap(code)};")
    for si, (sv, code) in enumerate(translated_dx):
        real = f"(({code}).real())" if use_complex else f"({code})"
        lines.append(
            f"    dxarr[(size_t){si} * (size_t)n_node * sw + nb + i] = (float){real};")
    lines.append("  }")
    lines.append("}")
    return "\n".join(lines), len(params), len(cvars), len(svars), list(params)


def emit_sources(models: dict = None, strict: bool = False,
                 entry_name: str = "cph_generic_dfun",
                 start_id: int = _FIRST_MODEL_ID):
    """Emit the expression-driven dfun C++ source plus its model metadata.

    Pure code emission: nothing is written to disk and nothing is compiled.
    Returns ``(source_text, meta)`` where ``meta`` maps model class name to
    ``dict(mid, n_parm, n_cvar, n_svar, parm_names)``.  ``parm_names`` is the
    ordered global+spatial parameter list the emitted kernel indexes ``parr``
    with, so callers can pack parameters without re-deriving them.

    The emitted TU carries that same ``meta`` as a C++ table (``cph_gen_entry``
    rows plus per-model parameter-name arrays, read through
    ``cph_builtin_count`` / ``cph_builtin_entry``), so a host that links the TU
    can look models up without going back through Python.  The table is built
    from ``meta`` itself, so ids, counts and parameter names cannot drift from
    the kernels they describe.

    Ids are assigned in sorted class-name order starting at ``start_id``
    (default ``_FIRST_MODEL_ID``, 100) and stay in lockstep with the emitted
    dispatch table, whose index is ``mid - _FIRST_MODEL_ID``.  A ``start_id``
    above ``_FIRST_MODEL_ID`` leaves that lower id range to another table — the
    one already compiled into the extension — and the dispatch table is
    gap-padded with ``nullptr`` for ``_FIRST_MODEL_ID .. start_id - 1``; the
    entry returns 0 for those slots, so such ids fall through to whoever owns
    them instead of calling a null pointer.  This is what lets a runtime library
    occupy an id range disjoint from the built-in one.

    ``entry_name`` names the emitted ``extern "C"`` entry symbol: the runtime
    fallback library uses ``cph_generic_dfun``, the prebuilt extension uses
    ``cph_builtin_dfun``.  The entry returns ``int`` — 1 when it handled
    ``model_id``, 0 when the id is outside this table — which is what lets the
    core fall back to another dfun source for ids it does not cover.

    ``models`` overrides model discovery (the runtime path uses it to inject
    user-defined models).  With ``strict=True``, every model module that failed
    to import and every model class that failed to configure or emit is raised
    as a single ``DfunGenerationError`` instead of being skipped.
    """
    if not entry_name.isidentifier():
        raise ValueError(f"invalid entry symbol name {entry_name!r}")
    if start_id < _FIRST_MODEL_ID:
        # ids below _FIRST_MODEL_ID are the hand-written kernels' range in
        # _core.cpp; a generated kernel there would never be dispatched
        raise ValueError(f"start_id {start_id} < {_FIRST_MODEL_ID} "
                         f"(the hand-written kernel range)")

    failures = []
    if models is None:
        models, failures = _collect_models()

    blocks = []
    meta = {}
    mid = start_id
    for name, model in sorted(models.items()):
        try:
            code, n_parm, n_cvar, n_svar, parm_names = _emit_model(
                mid, model, None)
        except Exception as exc:
            if strict:
                failures.append((f"{type(model).__module__}.{name}", "emit",
                                 _exc_text(exc)))
            continue
        blocks.append(code)
        meta[name] = dict(mid=mid, n_parm=n_parm, n_cvar=max(n_cvar, 1),
                          n_svar=n_svar, parm_names=parm_names)
        mid += 1
    if strict and failures:
        raise DfunGenerationError(_failure_report(failures))

    # Dispatch table slots, one per id from _FIRST_MODEL_ID.  Slots below
    # start_id are nullptr: this TU has no kernel for those ids (another table
    # owns them) and the entry's nullptr check returns 0 so the id falls
    # through to that owner rather than here.
    entries = ["  nullptr,"] * (start_id - _FIRST_MODEL_ID)
    entries.extend(f"  dfun_gen_{m['mid']}," for m in meta.values())
    n_slots = len(entries)
    if not entries:
        # nothing emitted: keep the array non-empty (C++ forbids a zero-sized
        # array); the bounds check below makes the entry unreachable
        entries = ["  nullptr,"]
        n_slots = 1
    table = "\n".join(entries)

    # Metadata table rows, built from the same ``meta`` dict returned to
    # Python callers (sorted by id, i.e. emission order) so the C++ view and
    # the Python view of the model set are the same data.
    name_arrays = []
    rows = []
    for name, m in sorted(meta.items(), key=lambda kv: kv[1]["mid"]):
        arr = f"_cph_parm_names_{m['mid']}"
        if m["parm_names"]:
            name_arrays.append("static const char *const %s[] = {%s};" % (
                arr, ", ".join(json.dumps(str(p)) for p in m["parm_names"])))
        else:
            # a parameter-less model still needs a non-empty array; the row's
            # n_parm == 0 keeps it unread
            name_arrays.append(
                f"static const char *const {arr}[] = {{nullptr}};")
        rows.append('  {"%s", %d, %d, %d, %d, %s},' % (
            name, m["mid"], m["n_parm"], m["n_cvar"], m["n_svar"], arr))
    if not rows:
        rows.append("  {nullptr, 0, 0, 0, 0, nullptr},")

    src = [_GENERATED_BANNER, _PRELUDE, """
extern "C" {
"""]
    src.extend(blocks)
    src.append("""
typedef void (*dfun_fn_t)(float*, const float*, int, int, int, int,
                          const float*, const float*, int, int);

static dfun_fn_t _dfuns[] = {
""")
    src.append(table)
    src.append("};\n")
    src.append("/* _dfuns slots == id - _FIRST_MODEL_ID; N_GEN_DFUNS is the slot "
               "count (gap-padded), N_GEN_MODELS the number of kernels. */\n")
    src.append(f"#define N_GEN_DFUNS {n_slots}\n")
    src.append(f"#define N_GEN_MODELS {len(meta)}\n")
    src.extend(name_arrays)
    src.append("""
/* One row per generated model: the C++ mirror of the metadata dict dfungen
 * hands to Python.  ``parm_names`` has ``n_parm`` entries in the order the
 * kernel indexes ``parr`` with.  _core.cpp redeclares this struct; the two
 * definitions must stay identical. */
typedef struct cph_gen_entry {
  const char *name;               /* model class name */
  int mid;                        /* model id (>= 100) */
  int n_parm, n_cvar, n_svar;     /* buffer shapes the kernel expects */
  const char *const *parm_names;  /* parr packing order */
} cph_gen_entry;

static const cph_gen_entry _cph_gen[] = {
""")
    src.append("\n".join(rows))
    src.append("};\n")
    src.append(f"""
/* Dispatch entry.  Returns 1 when ``model_id`` is in this table (and the
 * kernel ran), 0 when the id is unknown or lands on a gap-padded slot, so a
 * host dispatcher can fall back to another dfun source instead of silently
 * doing nothing or calling a null pointer. */
extern "C" CPH_GEN_EXPORT int {entry_name}(int model_id, float *dx,
                                           const float *x, int node, int mode,
                                           int n_node, int n_modes,
                                           const float *c, const float *p,
                                           int n_parm, int Wn) {{
  int idx = model_id - {_FIRST_MODEL_ID};
  if (idx < 0 || idx >= N_GEN_DFUNS) return 0;
  dfun_fn_t fn = _dfuns[idx];
  if (fn == nullptr) return 0;
  fn(dx, x, node, mode, n_node, n_modes, c, p, n_parm, Wn);
  return 1;
}}

/* Metadata accessors for _cph_gen, for idx in [0, N_GEN_MODELS).  Unlike
 * _dfuns, _cph_gen is compact: one row per emitted model, sorted by mid, so
 * its index is NOT an id offset when start_id > {_FIRST_MODEL_ID}; take
 * ``mid`` from the row itself. */
extern "C" CPH_GEN_EXPORT int cph_builtin_count(void) {{
  return N_GEN_MODELS;
}}

extern "C" CPH_GEN_EXPORT const cph_gen_entry *cph_builtin_entry(int idx) {{
  if (idx < 0 || idx >= N_GEN_MODELS) return nullptr;
  return &_cph_gen[idx];
}}

}}  // extern "C"
""")
    return "\n".join(src), meta


def generate_lib(cache_dir: Path, extra_models: dict = None,
                 start_id: int = _FIRST_MODEL_ID):
    """Generate + compile the generic dfun shared library (the runtime g++ /
    ctypes fallback path; stock models come from the prebuilt extension).

    ``start_id`` shifts the emitted ids so this library can occupy a range
    disjoint from the table already compiled into the extension (see
    ``emit_sources``); the dispatch table is gap-padded accordingly, so ids
    below ``start_id`` fall through to the built-in kernels instead of hitting
    a null slot.

    Returns (lib_path, model_ids, meta) where model_ids maps model class name
    to the integer id used in the dispatch table (ids >= 100) and meta is the
    emit_sources metadata.
    """
    cache_dir = Path(cache_dir)
    cache_dir.mkdir(parents=True, exist_ok=True)
    models = collect_models()
    if extra_models:
        models.update(extra_models)

    src, meta = emit_sources(models, start_id=start_id)
    src_path = cache_dir / "models_gen.cpp"
    src_path.write_text(src)
    so_path = cache_dir / "models_gen.so"
    inc = np.get_include()
    cmd = (f"g++ -O3 -march=native -fopenmp-simd -std=c++17 -fPIC -shared "
           f"-I{inc} {src_path} -o {so_path}")
    subprocess.run(cmd, shell=True, check=True, capture_output=True)
    model_ids = {name: m["mid"] for name, m in meta.items()}
    return so_path, model_ids, meta


_META_CACHE = None


def generate_meta():
    """Model metadata (ids/counts) for the generated library.

    Derived from emit_sources, so ids stay in lockstep with the emitted
    dispatch table.  Keys per model: mid, n_parm, n_cvar, n_svar, parm_names.
    """
    global _META_CACHE
    if _META_CACHE is None:
        _META_CACHE = emit_sources()[1]
    return _META_CACHE


# ---------------------------------------------------------------------------
# command line (invoked by the package build; emission only, no compilation)
# ---------------------------------------------------------------------------

def _main(argv=None) -> int:
    import argparse
    parser = argparse.ArgumentParser(
        prog="python -m tvb.simulator.backend.cpp_hybrid.dfungen",
        description="Emit the expression-driven C++ dfun source used by the "
                    "cpp_hybrid backend (no compilation).")
    parser.add_argument("--emit", required=True, metavar="PATH",
                        help="write the generated C++ source to PATH")
    parser.add_argument("--meta", metavar="PATH",
                        help="write the model metadata as JSON to PATH")
    parser.add_argument("--entry-name", default="cph_generic_dfun",
                        help='name of the emitted extern "C" entry symbol '
                             '(the prebuilt extension uses cph_builtin_dfun)')
    parser.add_argument("--strict", action="store_true",
                        help="fail if a model module cannot be imported or an "
                             "expression-driven model cannot be configured or "
                             "emitted, instead of skipping it")
    args = parser.parse_args(argv)
    try:
        src, meta = emit_sources(strict=args.strict, entry_name=args.entry_name)
        emit_path = Path(args.emit)
        emit_path.parent.mkdir(parents=True, exist_ok=True)
        emit_path.write_text(src)
        if args.meta:
            meta_path = Path(args.meta)
            meta_path.parent.mkdir(parents=True, exist_ok=True)
            meta_path.write_text(json.dumps(meta, indent=2, sort_keys=True)
                                 + "\n")
    except Exception as exc:
        print(f"dfungen: {exc}", file=sys.stderr)
        return 1
    print(f"dfungen: emitted {len(meta)} dfun(s), ids "
          f"{_FIRST_MODEL_ID}..{_FIRST_MODEL_ID + len(meta) - 1} -> {emit_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
