apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tvb-cloud
  namespace: tvb-official
spec:
  secretName: tvb-cloud
  renewBefore: 120h
  commonName: tvb-web.apps.tc.humanbrainproject.eu
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    - tvb-web.apps.tc.humanbrainproject.eu
  issuerRef:
    name: letsencrypt-production-issuer-1
    kind: ClusterIssuer