FROM python:3.7.7-windowsservercore

# Download miniconda
ADD https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe C:\\TEMP\\miniconda.exe

# Set our shell to became cmd
SHELL ["cmd", "/S", "/C"]

# Install miniconda
RUN start /wait "" C:\\TEMP\\miniconda.exe /InstallationType=AllUsers /RegisterPython=1 /S /D=C:\miniconda
RUN setx /M PATH "%PATH%;C:\miniconda\Scripts"
RUN conda init powershell

# Prepare tvb-run env
RUN activate && conda create -y --name tvb-run python=3.7 numba scipy numpy networkx scikit-learn cython pip numexpr psutil
RUN activate && conda install -y --name tvb-run pytest pytest-cov pytest-benchmark pytest-mock matplotlib-base
RUN activate && conda install -y --name tvb-run psycopg2 pytables scikit-image==0.14.2 simplejson cherrypy docutils werkzeug
RUN activate && conda install -y --name tvb-run -c conda-forge jupyterlab flask gevent

RUN activate tvb-run && pip install --upgrade pip
RUN activate tvb-run && pip install certifi
RUN activate tvb-run && pip install h5py==2.10 formencode cfflib jinja2 nibabel sqlalchemy alembic allensdk
RUN activate tvb-run && pip install tvb-gdist BeautifulSoup4 subprocess32 flask-restx python-keycloak mako pyAesCrypt pyunicore==0.6.0
RUN activate tvb-run && pip install autopep8

# Download and install tvb data
ADD https://zenodo.org/record/4263723/files/tvb_data.zip?download=1 C:\\TEMP\\tvb_data.zip
RUN powershell.exe -NoP -NonI -Command "Expand-Archive 'C:\\TEMP\\tvb_data.zip' 'C:\\tvb_data'"
RUN activate tvb-run && cd c:\\tvb_data && python setup.py develop

RUN mkdir %userprofile%\\TVB_TEST
RUN mkdir %userprofile%\\.tvb-temp
RUN CACLS %userprofile%\\TVB_TEST /e /p %username%:f
RUN CACLS %userprofile%\\.tvb-temp /e /p %username%:f

RUN powershell.exe rm C:\miniconda\envs\tvb-run\share\jupyter\kernels\python3\kernel.json
RUN echo {"argv": ["python.exe", "-m", ""ipykernel_launcher", "-f", "{connection_file}"], "display_name": "Python 3", "language": "python"} >> C:\miniconda\envs\tvb-run\share\jupyter\kernels\python3\kernel.json

CMD ["cmd", "activate tvb-run"]