FROM continuumio/miniconda3

ARG TVB_USER=tvb_user
ARG USER_HOME=/home/$TVB_USER
ARG TVB_STORAGE=$USER_HOME/TVB_STORAGE
ARG NUMBA_CACHE=$USER_HOME/numba_cache
ARG KEYCLOAK_CONFIG=$USER_HOME/keycloak_config
ARG JUPYTER_CONFIG=$USER_HOME/.jupyter

RUN useradd -ms /bin/bash $TVB_USER
WORKDIR $USER_HOME

RUN apt-get -y update && apt-get -y install build-essential gcc
RUN apt-get -y update && apt-get -y install texlive-base texlive-formats-extra
RUN apt-get -y update && apt-get -y install octave postgresql

USER postgres
RUN service postgresql start && createdb -O postgres tvb-test && psql --command "ALTER USER postgres WITH PASSWORD 'postgres';"

USER root
RUN conda update -n base -c defaults conda
RUN conda create -y --name tvb-run python=3 nomkl numba scipy numpy networkx scikit-learn cython pip numexpr psutil
RUN conda install -y --name tvb-run pytest pytest-cov pytest-benchmark pytest-mock matplotlib-base
RUN conda install -y --name tvb-run psycopg2 pytables scikit-image==0.14.2 simplejson cherrypy docutils werkzeug==0.16.1
RUN conda install -y --name tvb-run -c conda-forge jupyterlab flask gevent
RUN /opt/conda/envs/tvb-run/bin/pip install --upgrade pip
# Latest functioning pair compatible tested for sqlalchemy==1.3.20 sqlalchemy-migrate==0.13.0 h5py==3.1.0
RUN /opt/conda/envs/tvb-run/bin/pip install h5py formencode cfflib jinja2 nibabel sqlalchemy sqlalchemy-migrate allensdk
RUN /opt/conda/envs/tvb-run/bin/pip install tvb-gdist typing BeautifulSoup4 subprocess32 flask-restplus python-keycloak mako pyAesCrypt pyunicore

# Jupyther notebook configurations: set password
# tvb42
RUN mkdir $JUPYTER_CONFIG
RUN /bin/bash -c "source activate tvb-run"; \
    /opt/conda/envs/tvb-run/bin/jupyter notebook --generate-config; \
    echo "c.NotebookApp.password='sha1:12bff019c253:9daecd92c2e9bdb10b3b8a06767a74a0fe078d7c'">>$JUPYTER_CONFIG/jupyter_notebook_config.py

RUN wget https://zenodo.org/record/3688773/files/tvb-data.zip?download=1 -O tvb_data.zip; \
    mkdir tvb_data; unzip tvb_data.zip -d tvb_data; rm tvb_data.zip; \
    cd tvb_data; \
    /opt/conda/envs/tvb-run/bin/python setup.py develop

COPY --chown=$TVB_USER:$TVB_USER .tvb.configuration $USER_HOME/.tvb.configuration
RUN chown $TVB_USER:$TVB_USER $USER_HOME

USER $TVB_USER

RUN mkdir $USER_HOME/.tvb-temp; mkdir $USER_HOME/.tvb-temp/logs; mkdir -m777 $TVB_STORAGE $NUMBA_CACHE $KEYCLOAK_CONFIG

ENV TVB_USER_HOME $USER_HOME
ENV NUMBA_CACHE_DIR $NUMBA_CACHE

WORKDIR $USER_HOME/tvb-root
# MOUNT -v [local- tvb-root - clone]:$USER_HOME/tvb-root

# For running all unit-tests
# inspect output in local tvb-root/tvb_bin/TEST_OUTPUT folder
#CMD ["bash","-c","source activate tvb-run && cd tvb_build && bash install_full_tvb.sh && cd ../tvb_bin && service postgresql start && bash run_tests.sh postgres"]
