FROM python:3.10.5-windowsservercore-1809

WORKDIR /tmp
# Download and install miniconda
ADD https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe C:\\TEMP\\miniconda.exe
SHELL ["cmd", "/S", "/C"]
RUN start /wait "" C:\\TEMP\\miniconda.exe /InstallationType=AllUsers /RegisterPython=1 /S /D=C:\miniconda
RUN setx /M PATH "%PATH%;C:\miniconda\Scripts"
RUN conda init powershell

# Prepare tvb-run env
RUN activate && conda update -n base -c defaults conda
RUN activate && conda create -y --name tvb-run python=3.10 numba scipy numpy cython psycopg2
RUN activate && conda install -y --name tvb-run -c conda-forge jupyterlab tvb-gdist
RUN activate tvb-run && python -m pip install --upgrade pip
RUN activate tvb-run && pip install lockfile scikit-build
RUN activate tvb-run && pip install syncrypto


# Download and install tvb data
RUN mkdir C:\\TVB_CODE
WORKDIR /TVB_CODE
ADD https://zenodo.org/record/10128131/files/tvb_data.zip?download=1 tvb_data.zip
RUN tar -xf tvb_data.zip && dir && del tvb_data.zip
RUN activate tvb-run && python setup.py develop

COPY requirements_group requirements.txt
RUN activate tvb-run && pip install -r requirements.txt

RUN mkdir C:\\Users\\containeradministrator\\TVB_TEST
RUN mkdir C:\\Users\\containeradministrator\\.tvb-temp

CMD ["cmd", "activate tvb-run"]