FROM thevirtualbrain/tvb-run

ARG TVB_USER=tvb_user
RUN wget https://zenodo.org/record/4671396/files/tvb-migrate.zip?download=1 -O tvb-migrate.zip; \
unzip tvb-migrate.zip -d /home/tvb_user/TVB_STORAGE; rm tvb-migrate.zip;
RUN cd /home/tvb_user/TVB_STORAGE/tvb-migrate; cp -R PROJECTS ..; cp -R tvb-backup ..; cd ..; rm -R tvb-migrate;

USER root
RUN sed -i "s|URL_VALUE=sqlite:////home/tvb_user/TVB_STORAGE/tvb-database.db|URL_VALUE=postgresql+psycopg2://postgres:root@127.0.0.1:5432/tvb?user=postgres\&password=postgres|g" /home/tvb_user/.tvb.configuration;
RUN sed -i "s|SELECTED_DB=sqlite|SELECTED_DB=postgres|g" /home/tvb_user/.tvb.configuration;
RUN sed -i "s|LAST_CHECKED_FILE_VERSION=5|LAST_CHECKED_FILE_VERSION=4|g" /home/tvb_user/.tvb.configuration;
RUN sed -i "s|peer|trust|g" /etc/postgresql/11/main/pg_hba.conf;
CMD ["bash","-c","service postgresql start && createdb -U postgres tvb && pg_restore -U postgres -d tvb /home/tvb_user/TVB_STORAGE/tvb-migrate/TVB/tvb-backup && source activate tvb-run && cd tvb_bin &&  python -m run_migration"]
