FROM continuumio/miniconda3:master-nanoserver

# Set our shell to became cmd
SHELL ["cmd", "/S", "/C"]

# Prepare tvb-run env
RUN activate && conda update -n base -c defaults conda
RUN activate && conda create -y --name tvb-run python=3.10 numba scipy numpy cython psycopg2
RUN activate && conda install -y --name tvb-run -c conda-forge jupyterlab tvb-gdist
RUN activate tvb-run && pip install --upgrade pip
RUN activate tvb-run && pip install lockfile scikit-build
RUN activate tvb-run && pip install syncrypto

# Download and install tvb data
ADD https://zenodo.org/record/4263723/files/tvb_data.zip?download=1 C:\\TEMP\\tvb_data.zip
RUN Expand-Archive -Force 'C:\\TEMP\\tvb_data.zip' 'C:\\tvb_data'" && del C:\\TEMP\\tvb_data.zip
RUN activate tvb-run && cd c:\\tvb_data && python setup.py develop

COPY requirements_group requirements.txt
RUN activate tvb-run && pip install -r requirements.txt

RUN mkdir %userprofile%\\TVB_TEST
RUN mkdir %userprofile%\\.tvb-temp
RUN CACLS %userprofile%\\TVB_TEST /e /p %username%:f
RUN CACLS %userprofile%\\.tvb-temp /e /p %username%:f

CMD ["cmd", "activate tvb-run"]