FROM thevirtualbrain/tvb-run

ARG TVB_USER=tvb_user
COPY --chown=$TVB_USER:$TVB_USER TVB.zip /home/tvb_user/TVB_STORAGE
COPY --chown=$TVB_USER:$TVB_USER tvb-backup /tmp

USER root
RUN cd /home/tvb_user/TVB_STORAGE; unzip TVB.zip -d .; rm TVB.zip; cp -R TVB/PROJECTS .; rm -R TVB;
RUN sed -i "s|URL_VALUE=sqlite:////home/tvb_user/TVB_STORAGE/tvb-database.db|URL_VALUE=postgresql+psycopg2://postgres:root@127.0.0.1:5432/tvb?user=postgres\&password=postgres|g" /home/tvb_user/.tvb.configuration;
RUN sed -i "s|SELECTED_DB=sqlite|SELECTED_DB=postgres|g" /home/tvb_user/.tvb.configuration;
RUN sed -i "s|LAST_CHECKED_FILE_VERSION=5|LAST_CHECKED_FILE_VERSION=4|g" /home/tvb_user/.tvb.configuration;
RUN sed -i "s|peer|trust|g" /etc/postgresql/11/main/pg_hba.conf;
CMD ["bash","-c","service postgresql start && createdb -U postgres tvb && pg_restore -U postgres -d tvb /tmp/tvb-backup && source activate tvb-run && cd tvb_bin &&  python -m run_migration"]
