apiVersion: v1
kind: Template
metadata:
  name: thevirtualbrain
  annotations:
    description: "Template to create a cronjob that copies the database data into a backup volume"
    tags: "tvb, thevirtualbrain, hbp"
parameters:
  - name: POSTGRESQL_USER
    displayName: PostgreSQL default user
    description: User which will be used as default one for the PostgreSQL instance
    value: "tvb_db_user"
    required: true

  - name: POSTGRESQL_DATABASE
    displayName: PostgreSQL database name
    description: PostgreSQL database name
    value: "tvb_hbp_database"
    required: true

  - name: POSTGRESQL_PASSWORD
    displayName: PostgreSQL DB password
    description: Password that will be used to access the PostgreSQL DB
    value: ""
    required: true

objects:
  - kind: "PersistentVolumeClaim"
    apiVersion: v1
    metadata:
      name: backup
      annotations:
        volume.beta.kubernetes.io/storage-class: managed-nfs-storage
        volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "100Gi"

  - kind: CronJob
    apiVersion: batch/v1beta1
    metadata:
      name: tvb-postgres-backup
    spec:
      # ┌───────────── minute (0 - 59)
      # │ ┌───────────── hour (0 - 23)
      # │ │ ┌───────────── day of the month (1 - 31)
      # │ │ │ ┌───────────── month (1 - 12)
      # │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
      # │ │ │ │ │                                   7 is also Sunday on some systems)
      # │ │ │ │ │
      # │ │ │ │ │
      # * * * * *
      schedule: "0 0 * * 6"
      concurrencyPolicy: "Forbid"
      suspend: false
      successfulJobsHistoryLimit: 7
      failedJobsHistoryLimit: 7
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: tvb-postgres-backup
                  image: thevirtualbrain/okd_postgresql_backups:1.2
                  env:
                    - name: DATABASE_HOST
                      value: tvb-postgres
                    - name: DATABASE_NAME
                      value: ${POSTGRESQL_DATABASE}
                    - name: DATABASE_USER
                      value: ${POSTGRESQL_USER}
                    - name: DATABASE_PASS
                      value: ${POSTGRESQL_PASSWORD}
                  volumeMounts:
                    - name: backup
                      mountPath: /mnt
                  command: [ "/usr/local/bin/autopgsqlbackup.sh" ]
              volumes:
                - name: backup
                  persistentVolumeClaim:
                    claimName: backup
              restartPolicy: OnFailure