pipeline {
    agent any

    environment {
        FULL_DOCKER_IMAGE_NAME = 'docker-repository.codemart.ro/tvb-build'
        LATEST_TAG = 'latest'
        SVN_ACCESS  = credentials('933642b4-f11d-4c4c-8e2f-7d316127c0ce')
    }

    stages {
        stage ('Build docker image') {
            steps {
                script {
                    def dockerImage = docker.build("${FULL_DOCKER_IMAGE_NAME}:${env.BUILD_ID}", 'tvb_build/docker')
                    dockerImage.push()
                    dockerImage.push('${LATEST_TAG}')
                }
            }
        }
        stage ('Build TVB documentation') {
            agent {
                docker {
                    image '${FULL_DOCKER_IMAGE_NAME}:${LATEST_TAG}'
                }
            }
            steps {
                sh '''#!/bin/bash
                    svn upgrade --username ${SVN_ACCESS_USR} --password ${SVN_ACCESS_PSW}
                    source activate tvb-docs
                    cd tvb_build
                    sh install_full_tvb.sh
                    python build_step1.py
                '''
                archiveArtifacts artifacts: 'tvb_build/build/*.zip'
                stash includes: 'tvb_build/build/*.zip', name: 'docs-website'
            }
        }
        stage ('Run tests') {
            agent {
                docker {
                    image '${FULL_DOCKER_IMAGE_NAME}:${LATEST_TAG}'
                }
            }
            steps {
                sh '''#!/bin/bash
                    source activate tvb-run
                    cd tvb_build
                    sh install_full_tvb.sh
                    service postgresql start
                    cd ../tvb_bin
                    bash run_tests.sh postgres
                '''
            }
        }
        stage ('Build TVB') {
            agent {
                docker {
                    image '${FULL_DOCKER_IMAGE_NAME}:${LATEST_TAG}'
                }
            }
            steps {
                unstash 'docs-website'
                sh 'rm -R -f tvb_build/build/TVB_Distribution'
                sh '''#!/bin/bash
                    source activate tvb-run
                    cd tvb_build
                    sh install_full_tvb.sh
                    rm -R -f build/TVB_Distribution
                    python build_from_conda.py
                '''
                archiveArtifacts artifacts: 'tvb_build/build/TVB_Linux*.zip'
                junit 'tvb_bin/TEST_OUTPUT/TEST-*RESULTS.xml'
            }
        }
        stage ('Generate coverage') {
            agent {
                docker {
                    image '${FULL_DOCKER_IMAGE_NAME}:${LATEST_TAG}'
                }
            }
            steps {
                sh '''#!/bin/bash
                    source activate tvb-run
                    cd tvb_build
                    sh install_full_tvb.sh
                    cd ../scientific_library
                    py.test --cov-config .coveragerc --cov=tvb tvb/tests --cov-branch --cov-report xml:TEST_OUTPUT/coverage_library.xml --junitxml=TEST_OUTPUT/TEST-LIBRARY-RESULTS.xml
                '''
                junit 'scientific_library/TEST_OUTPUT/TEST-LIBRARY-RESULTS.xml'
                step([$class: 'CoberturaPublisher', autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'scientific_library/TEST_OUTPUT/coverage_library.xml', failUnhealthy: false, failUnstable: false, maxNumberOfBuilds: 0, onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false])
            }
        }
    }
    post {
        changed {
            mail to: 'lia.domide@codemart.ro, paula.popa@codemart.ro',
            subject: "Jenkins Pipeline ${currentBuild.fullDisplayName} changed status",
            body: """
                Result: ${currentBuild.result}
                Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'
                Check console output at ${env.BUILD_URL}"""
        }

        success {
            echo 'Build finished successfully'
        }
    }
}