apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '23'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.19.0.128","172.19.0.129","172.19.0.130","172.19.0.131","172.19.0.132","172.19.0.133","172.19.0.134","172.19.0.135"],"port":443,"protocol":"HTTPS","serviceName":"tvb:langing-page","ingressName":"tvb:start","hostname":"tvb.apps.tc.humanbrainproject.eu","path":"/","allNodes":false},{"port":31061,"protocol":"TCP","serviceName":"tvb:langing-page-nodeport","allNodes":true}]
  creationTimestamp: '2023-11-22T07:11:21Z'
  generation: 81
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-tvb-langing-page
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
          f:labels:
            .: {}
            f:workload.user.cattle.io/workloadselector: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:cattle.io/timestamp: {}
              f:labels:
                .: {}
                f:workload.user.cattle.io/workloadselector: {}
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"container-1"}:
                  .: {}
                  f:command: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":8080,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:privileged: {}
                    f:readOnlyRootFilesystem: {}
                    f:runAsNonRoot: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/home/.tvb.landing.page.configuration"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                      f:readOnly: {}
                      f:subPath: {}
                    k:{"mountPath":"/home/tvb_user/TVB_STORAGE"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsConfig: {}
              f:dnsPolicy: {}
              f:hostname: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:serviceAccount: {}
              f:serviceAccountName: {}
              f:subdomain: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"config-file"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                  f:name: {}
                k:{"name":"logs-folder"}:
                  .: {}
                  f:emptyDir:
                    .: {}
                    f:sizeLimit: {}
                  f:name: {}
      manager: agent
      operation: Update
      time: '2024-03-27T07:23:51Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:collisionCount: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2024-03-27T07:23:51Z'
  name: langing-page
  namespace: tvb
  resourceVersion: '155290493'
  uid: d57aeb02-72ba-4853-b184-4596ab12ca77
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-tvb-langing-page
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2024-03-06T11:19:28Z'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-tvb-langing-page
      namespace: tvb
    spec:
      containers:
        - command:
            - /bin/bash
            - '-c'
            - >-
              source activate tvb-run && python -m
              tvb.interfaces.web.run_landing_page
          image: thevirtualbrain/tvb-run:2.9
          imagePullPolicy: IfNotPresent
          name: container-1
          ports:
            - containerPort: 8080
              name: tvb
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/tvb_user/TVB_STORAGE
              name: logs-folder
            - mountPath: /home/.tvb.landing.page.configuration
              name: config-file
              readOnly: true
              subPath: file
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostname: tvb
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      subdomain: top
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: single-config-file
          name: config-file
        - emptyDir:
            sizeLimit: 2Gi
          name: logs-folder
status:
  availableReplicas: 1
  collisionCount: 1
  conditions:
    - lastTransitionTime: '2023-11-24T16:08:19Z'
      lastUpdateTime: '2024-03-20T12:15:35Z'
      message: ReplicaSet "langing-page-57bb88c5d4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2024-03-27T07:20:40Z'
      lastUpdateTime: '2024-03-27T07:20:40Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 81
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
